# The OS X Build Environment
# https://docs.travis-ci.com/user/reference/osx/#xcode-version

language: objective-c
xcode_project: GRDB.xcodeproj

# Caches
cache:
  - bundler
  - cocoapods

# Custom CocoaPods installation so that Podfile.lock is honored
install:
  - bundle install
  - bundle exec pod repo update

# Disable the default Travis-CI submodule logic
# The various make commands ensure that the appropriate submodules are retrieved
git:
  submodules: false

jobs:
  include:

    ###########################################
    ## Test GRDB Xcode 10.2
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBOSX (Swift 5, macOS)
      script: make test_framework_GRDBOSX_maxSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBOSX (Swift 4.2, macOS)
      script: make test_framework_GRDBOSX_minSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBWatchOS (watchOS)
      script: make test_framework_GRDBWatchOS
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 5, iOS <MAX>)
      script: make test_framework_GRDBiOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
      script: make test_framework_GRDBiOS_maxTarget_minSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 5, iOS <MIN>)
      script: make test_framework_GRDBiOS_minTarget
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBtvOS (Swift 5, tvOS <MAX>)
      script: make test_framework_GRDBtvOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBtvOS (Swift 4.2, tvOS <MAX>)
      script: make test_framework_GRDBtvOS_maxTarget_minSwift
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBtvOS (Swift 5, tvOS <MIN>)
      script: make test_framework_GRDBtvOS_minTarget
    
    - stage: Test GRDB Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDB [SPM] (macOS)
      script: make test_SPM
    
    ###########################################
    ## Test GRDBCustom Xcode 10.2
    
    - stage: Test GRDBCustom Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBOSX (Swift 5, macOS)
      script: make test_framework_GRDBCustomSQLiteOSX
    
    - stage: Test GRDBCustom Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 5, iOS <MAX>)
      script: make test_framework_GRDBCustomSQLiteiOS_maxTarget_maxSwift
    
    - stage: Test GRDBCustom Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
      script: make test_framework_GRDBCustomSQLiteiOS_maxTarget_minSwift
    
    - stage: Test GRDBCustom Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=GRDBiOS (Swift 5, iOS <MIN>)
      script: make test_framework_GRDBCustomSQLiteiOS_minTarget
    
    ###########################################
    ## Test SQLCipher Xcode 10.2
    
    - stage: Test SQLCipher Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=SQLCipher 3
      script: make test_framework_SQLCipher3
    
    - stage: Test SQLCipher Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=SQLCipher 4
      script: make test_framework_SQLCipher4
    
    ###########################################
    ## Test Installation Xcode 10.2
    
    # Manual Install
    - stage: Test Installation Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=Manual Install
      script: make test_install_manual
    
    # CocoaPods Lint
    - stage: Test Installation Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=CocoaPods Lint
      script: make test_CocoaPodsLint_GRDB
    
    # CocoaPods Install GRDB
    - stage: Test Installation Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=CocoaPods GRDB (framework)
      script: make test_install_GRDB_CocoaPods_framework
    
    # CocoaPods Install GRDB
    - stage: Test Installation Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=CocoaPods GRDB (static)
      script: make test_install_GRDB_CocoaPods_static
    
    # SPM Install
    - stage: Test Installation Xcode 10.2
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.2
      env:
        - TID=SPM
      script: make test_install_SPM
    
    ###########################################
    ## Test GRDB Xcode 10.1
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBOSX (Swift 4.2, macOS)
      script: make test_framework_GRDBOSX_maxSwift
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBWatchOS (watchOS)
      script: make test_framework_GRDBWatchOS
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
      script: make test_framework_GRDBiOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MIN>)
      script: make test_framework_GRDBiOS_minTarget
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBtvOS (Swift 4.2, tvOS <MAX>)
      script: make test_framework_GRDBtvOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDBtvOS (Swift 4.2, tvOS <MIN>)
      script: make test_framework_GRDBtvOS_minTarget
    
    - stage: Test GRDB Xcode 10.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10.1
      env:
        - TID=GRDB [SPM] (macOS)
      script: make test_SPM
    
    # ###########################################
    # ## Test GRDBCustom Xcode 10.1
    # 
    # - stage: Test GRDBCustom Xcode 10.1
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10.1
    #   env:
    #     - TID=GRDBOSX (Swift 4.2, macOS)
    #   script: make test_framework_GRDBCustomSQLiteOSX
    # 
    # - stage: Test GRDBCustom Xcode 10.1
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10.1
    #   env:
    #     - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
    #   script: make test_framework_GRDBCustomSQLiteiOS_maxTarget_maxSwift
    # 
    # - stage: Test GRDBCustom Xcode 10.1
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10.1
    #   env:
    #     - TID=GRDBiOS (Swift 4.2, iOS <MIN>)
    #   script: make test_framework_GRDBCustomSQLiteiOS_minTarget
    
    ###########################################
    ## Test GRDB Xcode 10
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBOSX (Swift 4.2, macOS)
      script: make test_framework_GRDBOSX_maxSwift
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBWatchOS (watchOS)
      script: make test_framework_GRDBWatchOS
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
      script: make test_framework_GRDBiOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBiOS (Swift 4.2, iOS <MIN>)
      script: make test_framework_GRDBiOS_minTarget
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBtvOS (Swift 4.2, tvOS <MAX>)
      script: make test_framework_GRDBtvOS_maxTarget_maxSwift
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDBtvOS (Swift 4.2, tvOS <MIN>)
      script: make test_framework_GRDBtvOS_minTarget
    
    - stage: Test GRDB Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=GRDB [SPM] (macOS)
      script: make test_SPM
    
    # ###########################################
    # ## Test GRDBCustom Xcode 10
    # 
    # - stage: Test GRDBCustom Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=GRDBOSX (Swift 4.2, macOS)
    #   script: make test_framework_GRDBCustomSQLiteOSX
    # 
    # - stage: Test GRDBCustom Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=GRDBiOS (Swift 4.2, iOS <MAX>)
    #   script: make test_framework_GRDBCustomSQLiteiOS_maxTarget_maxSwift
    # 
    # - stage: Test GRDBCustom Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=GRDBiOS (Swift 4.2, iOS <MIN>)
    #   script: make test_framework_GRDBCustomSQLiteiOS_minTarget
    # 
    # ###########################################
    # ## Test SQLCipher Xcode 10
    # 
    # - stage: Test SQLCipher Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=SQLCipher 3
    #   script: make test_framework_SQLCipher3
    # 
    # - stage: Test SQLCipher Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=SQLCipher 4
    #   script: make test_framework_SQLCipher4
    
    ###########################################
    ## Test Installation Xcode 10
    
    # # Manual Install
    # - stage: Test Installation Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=Manual Install
    #   script: make test_install_manual
    # 
    # # CocoaPods Lint
    # - stage: Test Installation Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=CocoaPods Lint
    #   script: make test_CocoaPodsLint_GRDB
    
    # CocoaPods Install GRDB
    - stage: Test Installation Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=CocoaPods GRDB (framework)
      script: make test_install_GRDB_CocoaPods_framework
    
    # CocoaPods Install GRDB
    - stage: Test Installation Xcode 10
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode10
      env:
        - TID=CocoaPods GRDB (static)
      script: make test_install_GRDB_CocoaPods_static
    
    # # SPM Install
    # - stage: Test Installation Xcode 10
    #   gemfile: .ci/gemfiles/Gemfile.travis
    #   osx_image: xcode10
    #   env:
    #     - TID=SPM
    #   script: make test_install_SPM
