# The OS X Build Environment
# https://docs.travis-ci.com/user/reference/osx/#Xcode-version

language: objective-c
xcode_project: GRDB.xcodeproj

# Disable the default Travis-CI submodule logic
# The various make commands ensure that the appropriate submodules are retrieved
git:
  submodules: false

jobs:
  include:

    ###########################################
    ## Test GRDB

    # Test GRDBOSX (Xcode 9.4)
    - stage: Test GRDB
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBOSX (Xcode 9.4, macOS)
      script: make test_framework_GRDBOSX

    # Test GRDBWatchOS (Xcode 9.4)
    - stage: Test GRDB
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBWatchOS (Xcode 9.4, watchOS)
      script: make test_framework_GRDBWatchOS

    # Test GRDBiOS (Xcode 9.4, iOS <MAXIMUM VERSION>)
    - stage: Test GRDB
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBiOS (Xcode 9.4, iOS <MAX>)
      script: make test_framework_GRDBiOS_maxTarget

    # Test GRDBiOS (Xcode 9.3, iOS <MINIMUM VERSION>))
    - stage: Test GRDB
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.3
      env:
        - TID=GRDBiOS (Xcode 9.3, iOS <MIN>)
      script: make test_framework_GRDBiOS_minTarget

    # Test GRDB [SPM] (Xcode 9.4, macOS)
    - stage: Test GRDB
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDB [SPM] (Xcode 9.4, macOS)
      script: make test_SPM

    ###########################################
    ## Test GRDB (Custom SQLite)

    # Test GRDBCustomSQLiteOSX (Xcode 9.4)
    - stage: Test GRDB + Custom SQLite
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBCustomSQLiteOSX (Xcode 9.4, macOS)
      script: make test_framework_GRDBCustomSQLiteOSX

    # Test GRDBCustomSQLiteiOS (Xcode 9.4, iOS <MAXIMUM VERSION>)
    - stage: Test GRDB + Custom SQLite
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBCustomSQLiteiOS (Xcode 9.4, iOS <MAX>)
      script: make test_framework_GRDBCustomSQLiteiOS_maxTarget

    # Test GRDBCustomSQLiteiOS (Xcode 9.3, iOS <MINIMUM VERSION>))
    - stage: Test GRDB + Custom SQLite
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.3
      env:
        - TID=GRDBCustomSQLiteiOS (Xcode 9.3, iOS <MIN>)
      script: make test_framework_GRDBCustomSQLiteiOS_minTarget

    ###########################################
    ## Test GRDB (SQLCipher)

    # Test GRDBCipherOSX (Xcode 9.4)
    - stage: Test GRDB + SQLCipher
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBCipherOSX (Xcode 9.4, macOS)
      script: make test_framework_GRDBCipherOSX

    # Test GRDBCipheriOS (Xcode 9.4, iOS <MAXIMUM VERSION>)
    - stage: Test GRDB + SQLCipher
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=GRDBCipheriOS (Xcode 9.4, iOS <MAX>)
      script: make test_framework_GRDBCipheriOS_maxTarget

    # Test GRDBCipheriOS (Xcode 9.3, iOS <MINIMUM VERSION>))
    - stage: Test GRDB + SQLCipher
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.3
      env:
        - TID=GRDBCipheriOS (Xcode 9.3, iOS <MIN>)
      script: make test_framework_GRDBCipheriOS_minTarget

    ###########################################
    ## Test Installation Methods

    # Manual Install (Xcode 9.4)
    - stage: Test Installation
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=Manual Install (Xcode 9.4)
      script: make test_install_manual

    # Manual Install (GRDBCipher, Xcode 9.4)
    - stage: Test Installation
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode9.4
      env:
        - TID=Manual Install (GRDBCipher, Xcode 9.4)
      script: make test_install_GRDBCipher

    # CocoaPods Lint (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods Lint GRDB.swift/default (Xcode 9.4)
      script: make test_CocoaPodsLint_GRDB_default

    # CocoaPods Lint (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods Lint GRDB.swift/3.19.3 (Xcode 9.4)
      script: make test_CocoaPodsLint_GRDB_3.19.3

    # CocoaPods Lint (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods Lint GRDBCipher (Xcode 9.4)
      script: make test_CocoaPodsLint_GRDBCipher

    # CocoaPods Install (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods GRDB (Xcode 9.4)
      script: make test_install_GRDB_CocoaPods

    # CocoaPods Install (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods GRDB+FTS5 (Xcode 9.4)
      script: make test_install_GRDBFTS5_CocoaPods

    # CocoaPods Install (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      install:
        - gem install cocoapods # Since Travis is not always on latest version
      env:
        - TID=CocoaPods GRDBCipher (Xcode 9.4)
      script: make test_install_GRDBCipher_CocoaPods

    # SPM Install (Xcode 9.4)
    - stage: Test Installation
      osx_image: xcode9.4
      env:
        - TID=SPM (Xcode 9.4)
      script: make test_install_SPM

    ## Carthage Build
    ## Commented out until `make test_CarthageBuild` performs *reliably*.
    ## See https://github.com/groue/GRDB.swift/pull/262
    # - stage: Test Installation
    #   osx_image: xcode9.4
    #   before_install:
    #     - brew update
    #     - brew outdated carthage || brew upgrade carthage
    #   env:
    #     - TID=Carthages
    #   script: make test_CarthageBuild
